---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову.
  - Пользователь должен иметь возможность искать товары по категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д. («т.д.» при формулировании требований лучше не использовать, а использовать конкретику. К примеру, дополнительно пользователь должен иметь возможность фильтровать по бренду, наличию товара).
  - Пользователь должен иметь возможность просматривать товары, пользуясь постраничным выводом.
  - Пользователь должен иметь возможность просматривать подробную информацию о товаре, а именно на странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Пользователь должен иметь возможность добавлять товары в корзину.
  - Пользователь должен иметь возможность просматривать содержимое корзины после добавления товаров.
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты, используя товар из корзины.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге. При этом нужные товары сохранятся в корзине.
  - Корзина хранится в сессии браузера.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика. (Лучше указывать, какое конкретно количество трафика).
  - Сайт должен быть доступен на различных устройствах.
  - Сайт — это SPA приложение, которое не перезагружает страницу.
implicit:
  - Добавляя товар в корзину, должна появляться иконка над корзиной, которая говорит о количестве товаров в ней. 
  - Кнопка очистки корзины и удаление товаров из корзины красного цвета.
  - На странице корзины должна отображаться общая сумма всех товаров в ней. 
  - Старая цена конкретного продукта в каталоге товаров должна быть перечёкнута и быть менее видимой, чем актуальная цена, если применяется скидка. 
